// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCa-xHUaGJdGgpm8QUIsd6u1q6yuiRJPRQ',
    appId: '1:81769276171:web:ed437ccd8b882edc53380e',
    messagingSenderId: '81769276171',
    projectId: 'easyfix-ae381',
    authDomain: 'easyfix-ae381.firebaseapp.com',
    storageBucket: 'easyfix-ae381.firebasestorage.app',
    measurementId: 'G-FT9VSZK149',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA439NAaYKN1LoSxe7XTOtZG0nslFkkORA',
    appId: '1:81769276171:android:fb8b7840d8ebcf4b53380e',
    messagingSenderId: '81769276171',
    projectId: 'easyfix-ae381',
    storageBucket: 'easyfix-ae381.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBujuZrS787HlWFIQhHr0tmyZ0mFvgaIDA',
    appId: '1:81769276171:ios:50b800a0b58260cd53380e',
    messagingSenderId: '81769276171',
    projectId: 'easyfix-ae381',
    storageBucket: 'easyfix-ae381.firebasestorage.app',
    iosClientId: '81769276171-a2kiavddn49p2ssagkqgniu3r03h0fpj.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

}